name: schedule
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  icalendar_parser: ^2.0.0
  google_fonts: ^6.3.2

  cupertino_icons: ^1.0.8
  animated_theme_switcher: ^2.0.10
  sidebarx: ^0.17.2
  lottie: ^3.3.2
  connectivity_plus: ^5.0.1
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  intl: ^0.20.2
  shared_preferences: ^2.2.0 # Оставить для сохранения темы и языка
  flutter_secure_storage: ^9.0.0
  flutter_launcher_icons: ^0.14.4

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter




  http: ^1.1.0 # Для загрузки расписания по ссылке
  icalendar_parser: ^2.0.0 # Для парсинга iCal-формата

  cupertino_icons: ^1.0.8
  animated_theme_switcher: ^2.0.10
  sidebarx: ^0.17.2
  lottie: ^3.3.2
  connectivity_plus: ^5.0.1
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  intl: ^0.20.2
  shared_preferences: ^2.2.0 # Оставить для сохранения темы и языка
  flutter_secure_storage: ^9.0.0


  flutter_localizations:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.png"